name: tests

on: [push, pull_request]

jobs:
  test:
    name: Mininet-Optical Emulation Tests
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2

      - name: Install Mininet (master)
        run: |
             git clone https://github.com/mininet/mininet
             mininet/util/install.sh -nv

      - name: Run Emulation tests
        run: make emutest
