name: tests

on: [push, pull_request]

jobs:
  test:
    name: Mininet-Optical Tests
    runs-on: ubuntu-latest
    steps:

      - name: apt update
        run:  sudo apt update

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Check out source code
        uses: actions/checkout@v2
            
      - name: Install Mininet-Optical dependencies (besides Mininet)
        run:  make depend

      - name: Build and install Mininet-Optical
        run: |
             make install
             pip3 show -f mininet-optical | grep examples

      # We pass empty PYTHONPATH in order to test the installed packages
      - name: Run Simulation Tests
        run: PYTHONPATH= make simtest

      - name: Install Mininet (master)
        run: |
             git clone https://github.com/mininet/mininet
             mininet/util/install.sh -nv

      - name: Run Emulation Tests
        run: PYTHONPATH= make emutest

      - name: Run OFC Demo Tests
        run: PYTHONPATH= make demotest
        
