name: tests

on: [push, pull_request]

jobs:
  test:
    name: Mininet-Optical Tests
    runs-on: ubuntu-latest
    steps:

      - name: apt update
        run:  sudo apt update

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build and install Mininet-Optical
        run:  pip install build && make install

      - name: Test "make depend"
        run:  make depend

      - name: Install Mininet (master)
        run: |
             git clone https://github.com/mininet/mininet
             mininet/util/install.sh -nv

      - name: Run Tests
        run: make test
